# FILENAME
# firewall_setup.yml
#
# DESCRIPTION
# Set up NGFW
#
# REQUIREMENTS
# pip install boto3
# pip install botocore
# pip install ansible
# ansible-galaxy install git+https://github.com/fvigo/ansible-pan.git
#
# STEPS
# update vars.yml with your own credentials/settings
#
# Good practice: The var files are provided in cleartext. They should be edited and encrypred using:
# ansible-vault encrypt firewall-secrets.yml
#
# EXECUTE
# ansible-playbook firewall_setup.yml
---
- hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - role: ansible-pan

  tasks:
    # load variables
    - name: include variables (free-form)
      include_vars: vars.yml
      no_log: 'yes'

    # wait for SSH
    - name: wait for SSH prompt (timeout 10min)
      wait_for: port=22 host="{{ngfw_ip}}" timeout=900

    # Set admin password
    - name: set admin password
      panos_admpwd: ip_address="{{ngfw_ip}}" key_filename="{{key_filename}}" newpassword="{{admin_password}}"
      register: result
      until: not result is failed
      retries: 10
      delay: 30

    # set NTP, DNS and Panorama
    - name: set dns and panorama
      panos_mgtconfig:
        ip_address: "{{ngfw_ip}}"
        password: "{{admin_password}}"
        dns_server_primary: "8.8.8.8"
        dns_server_secondary: "8.8.4.4"
        panorama_primary: "{{pano_ip}}"
        ntp_server_primary: "169.254.169.123"
    
    - pause: seconds=30

    - name: first authcode
      panos_lic:
        ip_address: "{{ngfw_ip}}"
        password: "{{admin_password}}"
        auth_code: "{{authcode1}}"
      register: result
    - name: Display serialnumber
      debug:
        var: "{{result.serialnumber}}"

    # the VM might restart
    - pause: seconds=30

    # check for 10 times, every 30 seconds, if device
    # is ready, using credentials admin/admin
    - name: wait for reboot
      panos_check:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
      register: result
      until: not result is failed
      retries: 10
      delay: 30

    - name: second authcode
      panos_lic:
        ip_address: "{{ngfw_ip}}"
        password: "{{admin_password}}"
        auth_code: "{{authcode2}}"
      register: result
    - name: Display serialnumber
      debug:
        var: "{{result.serialnumber}}"

    # update NGFW software
    - name: upgrade software
      panos_software:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        version: "latest"

    # check for 10 times, every 30 seconds, if device
    # is ready, using credentials admin/admin
    - name: wait for reboot
      panos_check:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
      register: result
      until: not result is failed
      retries: 10
      delay: 30
      
    # update content to latest release
    - name: update content
      panos_content:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        wildfire_update: yes
        content_update: yes
        anti_virus_update: yes

    # Create L3 Trust zone.
    - name: create Trust zone on firewall
      panos_zone:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        zone: 'L3-Trust'
        mode: 'layer3'
        enable_userid: true

    # Create L3 Untrust zone.
    - name: create Untrust zone on firewall
      panos_zone:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        zone: 'L3-Untrust'
        mode: 'layer3'

    # Management profile
    - name: internal mgmt profile
      panos_management_profile:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        name: 'Management'
        ping: true
        ssh: true
        userid_service: true
        response_pages: true
        https: true
        
    # Create ethernet1/2 as DHCP.
    - name: enable DHCP client on ethernet1/1 in zone external
      panos_interface:
        ip_address: '{{ ngfw_ip }}'
        username: '{{ admin_username }}'
        password: '{{ admin_password }}'
        if_name: "ethernet1/2"
        zone_name: "L3-Trust"
        management_profile: "Management"
        create_default_route: "no"
        operation: "update"
        commit: False

    # Create ethernet1/1 as DHCP.
    - name: enable DHCP client on ethernet1/2 in zone external
      panos_interface:
        ip_address: '{{ ngfw_ip }}'
        username: '{{ admin_username }}'
        password: '{{ admin_password }}'
        if_name: "ethernet1/1"
        zone_name: "L3-Untrust"
        create_default_route: "yes"
        operation: "update"
        commit: False

    - name: commit
      panos_commit:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
