# FILENAME
# firewall_setup.yml
#
# DESCRIPTION
# Set up NGFW
#
# REQUIREMENTS
# pip install boto3
# pip install botocore
# pip install ansible
# ansible-galaxy install git+https://github.com/fvigo/ansible-pan.git
#
# STEPS
# update vars.yml with your own credentials/settings
#
# Good practice: The var files are provided in cleartext. They should be edited and encrypred using:
# ansible-vault encrypt firewall-secrets.yml
#
# EXECUTE
# ansible-playbook firewall_setup.yml
---
- hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - role: ansible-pan

  tasks:
    # load variables
    - name: NGFW Include variables (free-form)
      include_vars: vars.yml
      no_log: 'yes'

    # wait for SSH
    - name: NGFW Wait for SSH prompt
      wait_for: port=22 host="{{ngfw_ip}}" timeout=900

    # Set admin password
    - name: NGFW Set admin password
      panos_admpwd: ip_address="{{ngfw_ip}}" key_filename="{{key_filename}}" newpassword="{{admin_password}}"
      register: result
      until: not result is failed
      retries: 30
      delay: 30

    # set Managment configuration and Panorama
    - name: NGFW Set Management and Panorama
      panos_mgtconfig:
        ip_address: "{{ngfw_ip}}"
        password: "{{admin_password}}"
        dns_server_primary: "8.8.8.8"
        dns_server_secondary: "8.8.4.4"
        panorama_primary: "{{pano_ip}}"
        ntp_server_primary: "169.254.169.123"
        hostname: "{{ngfw_hostname}}"
        domain: "{{domain}}"
        timezone: "{{timezone}}"
      register: result
      until: not result is failed
      retries: 2
      delay: 60

    - name: NGFW Add first authcode
      panos_lic:
        ip_address: "{{ngfw_ip}}"
        password: "{{admin_password}}"
        auth_code: "{{authcode1}}"
        force: true
      register: result
      until: not result is failed
      retries: 2
      delay: 60

    # Wait 60 seconds for restart to begin
    - pause: seconds=60

    # check for 10 times, every 30 seconds, if device
    # is ready, using credentials admin/admin
    - name: NGFW Wait for reboot
      panos_check:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
      register: result
      until: not result is failed
      retries: 10
      delay: 30

    - name: NGFW Add second authcode
      panos_lic:
        ip_address: "{{ngfw_ip}}"
        password: "{{admin_password}}"
        auth_code: "{{authcode2}}"
        force: true
      register: result
      until: not result is failed
      retries: 2
      delay: 60        

    # update NGFW software to latest release
    - name: NGFW Upgrade Software
      panos_software:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        version: "latest"
      register: result
      until: not result is failed
      retries: 2
      delay: 60        

    # check for 10 times, every 30 seconds, if device
    # is ready, using credentials admin/admin
    - name: NGFW Wait for reboot
      panos_check:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
      register: result
      until: not result is failed
      retries: 10
      delay: 30
      
    # update content to latest release
    - name: NGFW Update Content
      panos_content:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        wildfire_update: yes
        content_update: yes
        anti_virus_update: yes
      register: result
      until: not result is failed
      retries: 2
      delay: 60        

    # Create L3 Trust zone.
    - name: NGFW Create L3-Trust zone
      panos_zone:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        zone: 'L3-Trust'
        mode: 'layer3'
        enable_userid: true
      register: result
      until: not result is failed
      retries: 2
      delay: 60        

    # Create L3 Untrust zone.
    - name: NGFW Create L3-Untrust zone
      panos_zone:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        zone: 'L3-Untrust'
        mode: 'layer3'
      register: result
      until: not result is failed
      retries: 2
      delay: 60        

    # Management profile
    - name: NGFW Create Management profile
      panos_management_profile:
        ip_address: "{{ngfw_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        name: 'Management'
        ping: true
        ssh: true
        userid_service: true
        response_pages: true
        https: true
      register: result
      until: not result is failed
      retries: 2
      delay: 60        
        
    # Create ethernet1/2 in L3-Trust (DHCP with no default route)
    - name: NGFW Configure ethernet1/2 in zone L3-Trust with DHCP
      panos_interface:
        ip_address: '{{ ngfw_ip }}'
        username: '{{ admin_username }}'
        password: '{{ admin_password }}'
        if_name: "ethernet1/2"
        zone_name: "L3-Trust"
        management_profile: "Management"
        enable_dhcp: true
        create_default_route: false
        state: "present"
        commit: false
      register: result
      until: not result is failed
      retries: 2
      delay: 60        

    # Create ethernet1/1 in L3-Untrust (DHCP with default route)
    - name: NGFW Configure ethernet1/1 in zone L3-Untrust with DHCP
      panos_interface:
        ip_address: '{{ ngfw_ip }}'
        username: '{{ admin_username }}'
        password: '{{ admin_password }}'
        if_name: "ethernet1/1"
        zone_name: "L3-Untrust"
        enable_dhcp: true
        create_default_route: true
        state: "present"
        commit: true
      register: result
      until: not result is failed
      retries: 2
      delay: 60        
