# FILENAME
# panorama_setup.yml
#
# DESCRIPTION
# Set up Panorama
#
# REQUIREMENTS
# pip install boto3
# pip install botocore
# pip install ansible
# ansible-galaxy install git+https://github.com/fvigo/ansible-pan.git
#
# STEPS
# update vars.yml with your own credentials/settings
#
# Good practice: The var files are provided in cleartext. They should be edited and encrypred using:
# ansible-vault encrypt firewall-secrets.yml
#
# EXECUTE
# ansible-playbook panorama_setup.yml
---
- hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - role: ansible-pan

  tasks:
    # load variables
    - name: include variables (free-form)
      include_vars: vars.yml
      no_log: 'yes'

    # wait for SSH
    - name: wait for SSH prompt (timeout 10min)
      wait_for: port=22 host="{{pano_ip}}" timeout=900

    # Set serial and admin password
    - name: set admin password and serial
      panorama_pass_serial: ip_address="{{pano_ip}}" key_filename="{{key_filename}}" newpassword="{{admin_password}}" serial="{{pano_serial}}"
      register: result
      until: not result is failed
      retries: 10
      delay: 30

    # set NTP and DNS
    - name: set ntp and dns
      panos_mgtconfig:
        ip_address: "{{pano_ip}}"
        password: "{{admin_password}}"
        dns_server_primary: "8.8.8.8"
        dns_server_secondary: "8.8.4.4"
        ntp_server_primary: "169.254.169.123"

    - name: pano fetch license
      panos_lic:
        ip_address: "{{pano_ip}}"
        password: "{{admin_password}}"
      register: result
    - name: Display serialnumber
      debug:
        var: "{{result.serialnumber}}"

    # update Panorama software
    - name: upgrade software
      panos_software:
        ip_address: "{{pano_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        version: "latest"
        restart: true

    # check for 10 times, every 30 seconds, if Panorama
    # is ready, using credentials admin/admin
    - name: wait for reboot
      panos_check:
        ip_address: "{{pano_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
      register: result
      until: not result is failed
      retries: 10
      delay: 30

    # install Cloud Services Plugin
    - name: install plugin
      panorama_plugin:
        ip_address: "{{pano_ip}}"
        password: "{{admin_password}}"
        plugin: "{{cloud_plugin}}"
